version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  web:
    build: .
    volumes:
      - .:/home/docker/code
    ports:
      - 8000:80
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080